const pptxgen = require('pptxgenjs');
const pptx = new pptxgen();
pptx.defineLayout({ name: 'WIDE_CUSTOM', width: 13.333, height: 7.5 });
pptx.layout = 'WIDE_CUSTOM'; pptx.author = 'Razorpay Buildathon Team'; pptx.company = 'Razorpay Buildathon';
pptx.subject = 'Universal AI-Commerce Adapter for Razorpay Merchants'; pptx.title = 'Razorpay AI-Commerce Adapter';
pptx.lang = 'en-IN'; pptx.theme = { headFontFace: 'Georgia', bodyFontFace: 'Aptos', lang: 'en-IN' }; pptx.margin = 0;
const C = { navy:'0B1F3A', ink:'16263A', blue:'2B84EA', blueDark:'1769D1', blueLight:'EAF3FF', pale:'F7FAFF', line:'C8DDF5', muted:'60738A', white:'FFFFFF', success:'16836A', darkBg:'0A1B33', darkCard:'132B4B', lightText:'D7E7FA' };
const S = pptx.ShapeType;
function base(s,n,d=false){s.background={color:d?C.darkBg:C.pale};if(!d)s.addShape(S.rect,{x:0,y:0,w:13.333,h:.12,fill:{color:C.blue},line:{color:C.blue}});s.addText('RAZORPAY BUILDATHON  /  TRACK 1 · AI GROWTH & AGENTIC COMMERCE',{x:.7,y:7.05,w:5.5,h:.12,fontFace:'Aptos',fontSize:7.2,bold:true,charSpacing:1.05,color:d?'8EBEF4':C.muted,margin:0});s.addText(String(n).padStart(2,'0'),{x:12.1,y:7.03,w:.5,h:.14,fontFace:'Aptos',fontSize:8,bold:true,color:d?'8EBEF4':C.muted,margin:0,align:'right'});}
function header(s,e,t,n,d=false){base(s,n,d);s.addText(e.toUpperCase(),{x:.7,y:.58,w:7.8,h:.16,fontFace:'Aptos',fontSize:8.5,bold:true,charSpacing:2.1,color:C.blue,margin:0});s.addText(t,{x:.68,y:.89,w:11.85,h:.64,fontFace:'Georgia',fontSize:25,bold:true,color:d?C.white:C.ink,margin:0,fit:'shrink'});}
function rounded(s,x,y,w,h,fill,line=fill){s.addShape(S.roundRect,{x,y,w,h,rectRadius:.08,fill:{color:fill},line:{color:line,width:.7}});}
function card(s,x,y,w,h,icon,title,body,accent=C.blue){rounded(s,x,y,w,h,C.white,C.line);s.addShape(S.ellipse,{x:x+.25,y:y+.26,w:.48,h:.48,fill:{color:accent},line:{color:accent}});s.addText(icon,{x:x+.25,y:y+.365,w:.48,h:.16,fontFace:'Aptos',fontSize:12,bold:true,color:C.white,margin:0,align:'center'});s.addText(title,{x:x+.25,y:y+.9,w:w-.5,h:.27,fontFace:'Georgia',fontSize:13.5,bold:true,color:C.ink,margin:0,fit:'shrink'});s.addText(body,{x:x+.25,y:y+1.34,w:w-.5,h:h-1.52,fontFace:'Aptos',fontSize:9.3,color:C.muted,margin:0,fit:'shrink',valign:'top'});}
function takeaway(s,label,text,d=false){rounded(s,.7,6.06,11.93,.62,d?C.darkCard:C.blueLight,d?C.darkCard:C.line);s.addText(label.toUpperCase(),{x:.96,y:6.22,w:1.25,h:.12,fontFace:'Aptos',fontSize:7.3,bold:true,charSpacing:1.4,color:C.blue,margin:0});s.addText(text,{x:.96,y:6.39,w:11.3,h:.16,fontFace:'Aptos',fontSize:9.5,color:d?C.white:C.ink,margin:0,fit:'shrink'});}
function arrow(s,x,y,w=.32,color=C.blue){s.addText('→',{x,y,w,h:.25,fontFace:'Aptos',fontSize:17,bold:true,color,margin:0,align:'center'});}
// 01 Cover
{const s=pptx.addSlide();s.background={color:'F9FBFF'};s.addShape(S.rect,{x:9.74,y:0,w:3.593,h:7.5,fill:{color:C.navy},line:{color:C.navy}});s.addShape(S.arc,{x:9.15,y:.62,w:4.02,h:4.02,adjustPoint:.3,rotate:20,line:{color:C.blue,transparency:10,width:2},fill:{color:C.navy,transparency:100}});s.addShape(S.arc,{x:10.22,y:2.15,w:3.05,h:3.05,adjustPoint:.3,rotate:200,line:{color:'69A8F2',transparency:30,width:1.5},fill:{color:C.navy,transparency:100}});s.addShape(S.ellipse,{x:10.68,y:1.53,w:1.65,h:1.65,fill:{color:C.blue},line:{color:C.blue}});s.addShape(S.ellipse,{x:11.22,y:2.08,w:.56,h:.56,fill:{color:C.white},line:{color:C.white}});rounded(s,.68,.55,.32,.32,C.blue,C.blue);s.addText('R',{x:.762,y:.592,w:.16,h:.15,fontFace:'Aptos',fontSize:8,bold:true,color:C.white,margin:0,align:'center'});s.addText('razorpay',{x:1.08,y:.55,w:1.2,h:.28,fontFace:'Aptos',fontSize:14,bold:true,color:C.navy,margin:0});s.addText('BUILDATHON 2026  /  TRACK 1 · AI GROWTH & AGENTIC COMMERCE',{x:.7,y:1.62,w:7.6,h:.22,fontFace:'Aptos',fontSize:8.5,bold:true,charSpacing:2.1,color:C.blue,margin:0});s.addText('The trusted payment layer\nfor agentic commerce.',{x:.68,y:2,w:8.55,h:1.62,fontFace:'Georgia',fontSize:31,bold:true,color:C.navy,margin:0,fit:'shrink'});s.addShape(S.line,{x:.7,y:4.06,w:1.05,h:0,line:{color:C.blue,width:2.1}});s.addText('Universal AI-Commerce Adapter for Razorpay Merchants',{x:.7,y:4.31,w:7.65,h:.34,fontFace:'Aptos',fontSize:15.5,color:C.navy,margin:0,fit:'shrink'});s.addText('Let every merchant become AI-discoverable, while Razorpay keeps every autonomous purchase secure, approved and auditable.',{x:.7,y:4.85,w:7.7,h:.58,fontFace:'Aptos',fontSize:11.5,color:C.muted,margin:0,fit:'shrink'});rounded(s,.7,6.25,3.2,.47,C.blueLight,C.line);s.addText('MCP  ·  AI discovery  ·  Razorpay rails',{x:.89,y:6.38,w:2.83,h:.13,fontFace:'Aptos',fontSize:8.5,bold:true,color:C.blueDark,margin:0,align:'center'});s.addText('RAZORPAY BUILDATHON',{x:.7,y:7.04,w:2.5,h:.14,fontFace:'Aptos',fontSize:7.5,bold:true,charSpacing:1.25,color:C.muted,margin:0});s.addText('01',{x:12.34,y:7.03,w:.42,h:.14,fontFace:'Aptos',fontSize:8,bold:true,color:'78ACE5',margin:0,align:'right'});}
// 02 Problem
{const s=pptx.addSlide();header(s,'The broken moment','AI can discover a product — but checkout still breaks.',2);const a=[['ASK','“Find a leather jacket under ₹8,000”'],['FIND','AI discovers a relevant product'],['BREAK','Buyer leaves AI to browse, search and fill forms'],['LOSE','Merchant loses the intent-rich conversion']];a.forEach((v,i)=>{let x=.7+i*3.05;rounded(s,x,2.1,2.57,2.72,i===2?'FFF2F1':C.white,i===2?'F8CAC6':C.line);s.addText(v[0],{x:x+.25,y:2.4,w:2.07,h:.18,fontFace:'Aptos',fontSize:8,bold:true,charSpacing:1.5,color:i===2?'CD4E43':C.blue,margin:0});s.addText(String(i+1),{x:x+.25,y:2.83,w:.5,h:.5,fontFace:'Georgia',fontSize:25,bold:true,color:i===2?'CD4E43':C.blue,margin:0});s.addText(v[1],{x:x+.25,y:3.58,w:2.05,h:.72,fontFace:'Aptos',fontSize:12,bold:true,color:C.ink,margin:0,fit:'shrink'});if(i<3)arrow(s,x+2.59,3.28)});takeaway(s,'The gap','Agentic commerce needs a trusted action layer — not just another product search experience.');}
// 03 Solution
{const s=pptx.addSlide();header(s,'Proposed solution','One platform. Two secure interfaces. One trusted transaction flow.',3);card(s,.7,1.92,5.66,3.55,'↗','Vendor API','Register and update inventory · create Razorpay orders · verify payment signatures · get AI cross-sell recommendations · set merchant auto-purchase limits.');card(s,6.97,1.92,5.66,3.55,'✦','MCP server for AI agents','A buyer adds our MCP server to Claude, ChatGPT, Gemini or any LLM agent. Seven commerce tools let the agent discover, check, recommend and transact securely.',C.success);s.addShape(S.line,{x:6.43,y:3.15,w:.47,h:0,line:{color:C.blue,width:1.4,beginArrowType:'none',endArrowType:'triangle'}});s.addText('HITL',{x:6.28,y:3.43,w:.78,h:.16,fontFace:'Aptos',fontSize:7.5,bold:true,color:C.blueDark,align:'center',margin:0});takeaway(s,'Dual controls','Below configured limits, AI can complete a purchase automatically. Above either merchant or buyer limit, Human-in-the-Loop approval is required.');}
// 04 Merchant
{const s=pptx.addSlide();header(s,'Merchant side','Lightweight adapter for any e-commerce stack.',4);const a=[['01','Shopify & WP','Designed for 1-click app & plugin distribution.'],['02','Python & Node','Paste 1 line of router middleware to expose MCP tools.'],['03','Zero Rewrite','Connects directly to existing catalog & Razorpay rails.']];a.forEach((v,i)=>{let x=.7+i*4.05;rounded(s,x,2.05,3.56,2.4,C.white,C.line);s.addText(v[0],{x:x+.28,y:2.35,w:.5,h:.2,fontFace:'Aptos',fontSize:9,bold:true,color:C.blue,margin:0});s.addText(v[1],{x:x+.28,y:2.85,w:2.85,h:.3,fontFace:'Georgia',fontSize:18,bold:true,color:C.ink,margin:0});s.addText(v[2],{x:x+.28,y:3.42,w:2.9,h:.48,fontFace:'Aptos',fontSize:10,color:C.muted,margin:0,fit:'shrink'})});rounded(s,.7,4.93,11.93,.62,C.navy,C.navy);s.addText('STANDARD CAPABILITIES EXPOSED',{x:.96,y:5.1,w:2.65,h:.12,fontFace:'Aptos',fontSize:7.3,bold:true,charSpacing:1.3,color:'8EBEF4',margin:0});s.addText('Inventory sync   ·   discovery   ·   policy checks   ·   AI cross-sell   ·   Razorpay order & payment verification',{x:.96,y:5.29,w:10.8,h:.14,fontFace:'Aptos',fontSize:9.8,color:C.white,margin:0,fit:'shrink'});takeaway(s,'Merchant value','Become AI-discoverable without replacing the existing storefront or payment workflow.');}
// 05 Buyer
{const s=pptx.addSlide();header(s,'Buyer side','Your favourite AI assistant becomes a trusted shopper.',5);const a=[['1','Connect','Add the Razorpay MCP server URL'],['2','Ask','“Find a genuine leather jacket under ₹5,000”'],['3','Evaluate','Compare products, stock, policy and price'],['4','Buy','Pay automatically — or approve when required']];a.forEach((v,i)=>{let x=.7+i*3.06;rounded(s,x,2.18,2.58,2.65,i===3?C.blue:C.white,i===3?C.blue:C.line);s.addShape(S.ellipse,{x:x+.96,y:2.46,w:.64,h:.64,fill:{color:i===3?C.white:C.blue},line:{color:i===3?C.white:C.blue}});s.addText(v[0],{x:x+.96,y:2.66,w:.64,h:.15,fontFace:'Aptos',fontSize:10,bold:true,color:i===3?C.blue:C.white,margin:0,align:'center'});s.addText(v[1],{x:x+.24,y:3.43,w:2.1,h:.22,fontFace:'Georgia',fontSize:14,bold:true,color:i===3?C.white:C.ink,margin:0,align:'center'});s.addText(v[2],{x:x+.22,y:3.9,w:2.14,h:.45,fontFace:'Aptos',fontSize:9.2,color:i===3?'E7F2FF':C.muted,margin:0,fit:'shrink',align:'center'});if(i<3)arrow(s,x+2.6,3.24)});takeaway(s,'Buyer control','Natural-language shopping stays bounded by the buyer’s approval limit and the merchant’s transaction policy.');}
// 06 Network
{const s=pptx.addSlide();header(s,'Network architecture','Multi-store routing vision for the Razorpay network.',6,true);const a=[{x:.7,w:2.35,t:'Buyer AI Agent',b:'ChatGPT · Claude · Gemini'},{x:4.03,w:3.05,t:'Razorpay Multi-Store\nCommerce Hub (Vision)',b:'Compare · rank · route'},{x:9.18,w:3.45,t:'Participating merchants',b:'Catalogs · inventory · policies'}];a.forEach((v,i)=>{rounded(s,v.x,2.42,v.w,1.47,i===1?C.blue:C.darkCard,i===1?C.blue:'2B4B70');s.addText(v.t,{x:v.x+.22,y:2.78,w:v.w-.44,h:.38,fontFace:'Georgia',fontSize:i===1?15:14,bold:true,color:C.white,margin:0,align:'center',fit:'shrink'});s.addText(v.b,{x:v.x+.22,y:3.38,w:v.w-.44,h:.14,fontFace:'Aptos',fontSize:8.5,bold:true,color:i===1?'EAF4FF':'AFC8E5',margin:0,align:'center'})});arrow(s,3.05,2.98,.75,'69A8F2');arrow(s,7.42,2.98,1.25,'69A8F2');['Product match','Stock & delivery','Price & policy'].forEach((v,i)=>{rounded(s,2.18+i*3.08,4.62,2.68,.53,C.darkCard,'2B4B70');s.addText(v,{x:2.18+i*3.08,y:4.8,w:2.68,h:.12,fontFace:'Aptos',fontSize:8.5,bold:true,color:C.lightText,margin:0,align:'center'})});takeaway(s,'Network effect','Our MCP adapter provides the foundational node engine for Razorpay to aggregate merchants into an AI-searchable network.',true);}
// 07 Flow
{const s=pptx.addSlide();header(s,'Live flow','Autonomous where safe. Human where it matters.',7);const a=[['01','Search','Find the ₹4,499 jacket'],['02','Cross-sell','Offer complementary item'],['03','Guardrail','Verify budget & price integrity'],['04','Approve','Human approval if limit exceeded'],['05','Pay','Create order · capture · audit log']];a.forEach((v,i)=>{let x=.7+i*2.4;rounded(s,x,2.08,2.06,2.72,i===3?'EAF3FF':C.white,i===3?'91C0F3':C.line);s.addText(v[0],{x:x+.22,y:2.35,w:.4,h:.14,fontFace:'Aptos',fontSize:8,bold:true,color:C.blue,margin:0});s.addText(v[1],{x:x+.22,y:2.9,w:1.6,h:.25,fontFace:'Georgia',fontSize:14,bold:true,color:C.ink,margin:0,fit:'shrink'});s.addText(v[2],{x:x+.22,y:3.49,w:1.62,h:.55,fontFace:'Aptos',fontSize:9.2,color:C.muted,margin:0,fit:'shrink'});if(i<4)arrow(s,x+2.05,3.19,.3)});rounded(s,.7,5.25,11.93,.45,'EAF8F4','B4E6D5');s.addText('✓  Every completed payment is verified and recorded, with live audit logs visible on the merchant dashboard.',{x:.98,y:5.4,w:11.15,h:.14,fontFace:'Aptos',fontSize:9.5,bold:true,color:'126952',margin:0,fit:'shrink'});takeaway(s,'Trust by design','Configured limits determine the path: direct payment below threshold; explicit approval above it.');}
// 08 Future
{const s=pptx.addSlide();header(s,'Future enhancements','The foundation for a richer agentic commerce ecosystem.',8);const a=[['↻','Multi-vendor routing','Federated search & comparison across merchant network'],['⌁','Platform plugins','Off-the-shelf Shopify App Store & WooCommerce plugins'],['＋','Commerce depth','Carts, subscriptions, refunds and support via MCP'],['◈','Trust intelligence','Risk scoring, anomaly detection and merchant analytics']];a.forEach((v,i)=>card(s,.7+(i%2)*6.12,1.87+Math.floor(i/2)*1.88,5.72,1.45,v[0],v[1],v[2],i===3?C.success:C.blue));takeaway(s,'Roadmap','Expand from secure product discovery and payment into the complete, intelligent purchase lifecycle.');}
// 09 Conclusion
{const s=pptx.addSlide();header(s,'Conclusion','Razorpay can power trusted autonomous commerce.',9,true);const a=[['MERCHANTS','Become AI-ready\nwithout rebuilding stores.'],['BUYERS','Shop naturally with\nclear approval control.'],['RAZORPAY','Power the trusted transaction\nlayer of the agentic economy.']];a.forEach((v,i)=>{let x=.7+i*4.05;rounded(s,x,2.05,3.56,2.16,i===2?C.blue:C.darkCard,i===2?C.blue:'2B4B70');s.addText(v[0],{x:x+.28,y:2.43,w:2.95,h:.14,fontFace:'Aptos',fontSize:8,bold:true,charSpacing:1.4,color:i===2?'EAF4FF':'8EBEF4',margin:0,align:'center'});s.addText(v[1],{x:x+.28,y:3.03,w:2.95,h:.55,fontFace:'Georgia',fontSize:14,bold:true,color:C.white,margin:0,align:'center',fit:'shrink'})});s.addShape(S.line,{x:3.45,y:5.02,w:6.44,h:0,line:{color:C.blue,width:1.5}});s.addText('From payment gateway to the financial backbone of the global agentic economy.',{x:1.25,y:5.28,w:10.84,h:.35,fontFace:'Georgia',fontSize:17,bold:true,italic:true,color:C.white,margin:0,align:'center',fit:'shrink'});s.addText('Thank you',{x:5.8,y:6.17,w:1.73,h:.25,fontFace:'Aptos',fontSize:11,bold:true,color:'8EBEF4',margin:0,align:'center'});}
pptx.writeFile({ fileName: 'Razorpay_AI_Commerce_Adapter_Deck.pptx' });
