from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, ConfigDict

class PaymentMethod(str, Enum):
    CARD = "card"
    UPI = "upi"
    NETBANKING = "netbanking"
    WALLET = "wallet"
    MOCK = "mock"

class RazorpayOrderCreateRequest(BaseModel):
    order_id: str = Field(..., description="Internal order ID (e.g. ORD-20260825-XXXXXX)")
    receipt: Optional[str] = Field(None, description="Optional custom receipt reference")
    notes: Optional[Dict[str, str]] = Field(default_factory=dict, description="Custom metadata notes")

class RazorpayOrderResponse(BaseModel):
    success: bool = Field(..., description="True if order creation succeeded")
    razorpay_order_id: str = Field(..., description="Razorpay Order ID (e.g. order_rzp_12345)")
    internal_order_id: str = Field(..., description="Internal order ID")
    amount_in_paise: int = Field(..., description="Order amount in Paise (1 INR = 100 Paise)")
    amount_in_inr: float = Field(..., description="Order amount in INR")
    currency: str = Field(default="INR", description="Currency code")
    status: str = Field(..., description="Razorpay order status (e.g. created)")
    created_at: Optional[str] = None

class PaymentLinkCreateRequest(BaseModel):
    order_id: str = Field(..., description="Internal order ID requiring step-up authorization")
    description: Optional[str] = Field(default="Human Step-up Authorization for High-Value Purchase", description="Description for buyer payment link")
    callback_url: Optional[str] = Field(None, description="URL to redirect buyer upon payment completion")

class PaymentLinkResponse(BaseModel):
    success: bool = Field(..., description="True if payment link generation succeeded")
    payment_link_id: str = Field(..., description="Unique Razorpay payment link ID (e.g. plink_12345)")
    payment_link_url: str = Field(..., description="Checkout URL for buyer to complete payment")
    internal_order_id: str = Field(..., description="Internal order ID")
    amount_inr: float = Field(..., description="Payment amount in INR")
    status: str = Field(..., description="Link status (e.g. created, active)")
    expire_by: Optional[int] = Field(None, description="Unix timestamp when payment link expires")

class PaymentVerificationRequest(BaseModel):
    internal_order_id: str = Field(..., description="Internal order ID")
    razorpay_order_id: str = Field(..., description="Razorpay Order ID")
    razorpay_payment_id: str = Field(..., description="Razorpay Payment ID")
    razorpay_signature: str = Field(..., description="HMAC SHA-256 signature generated by Razorpay Checkout")

class PaymentVerificationResponse(BaseModel):
    success: bool = Field(..., description="True if HMAC signature is valid and payment is verified")
    internal_order_id: str = Field(..., description="Internal order ID")
    current_state: str = Field(..., description="Current state in order state machine (e.g. RAZORPAY_CAPTURED)")
    message: str = Field(..., description="Detailed verification status message")

class WebhookPayload(BaseModel):
    entity: str = Field(default="event", description="Entity type")
    event: str = Field(..., description="Razorpay event name (e.g. payment.captured, payment.failed)")
    contains: List[str] = Field(default_factory=list, description="Entities included in payload")
    payload: Dict[str, Any] = Field(..., description="Event payload dictionary")
    created_at: Optional[int] = None
